### PR TITLE
update versions of miniconda and rstudio

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
This PR really just bumps the RStudio version and the Miniconda version.

I think the ie2 branch was the latest? Thats what I based it on and thats why the diff looks so odd.

@hexylena who do you want to proceed?

* We should rename master to main at some point. 
* add some CI testing (maybe https://github.com/usegalaxy-eu/docker-divand/tree/main/.github/workflows)

**Comment by bgruening** [comment]
The last commit adds some larger restructuring.

* It uses miniforge
* activate the mamba solver by default for conda
* it removed some deps that are hopefully not needed anymore
* and it removed nginx - it seems we have not used nginx in the last release at all

I'm unsure about the PROXY_PREFIX and if this is still needed for other deployments than EU, ORG ...

The container is available here https://quay.io/repository/galaxy/docker-rstudio-notebook

**Comment by bgruening** [comment]
Its deployed on EU, if you would like to test.

**Comment by hexylena** [comment]
> The last commit adds some larger restructuring.

very cool!

**Comment by hexylena** [comment]
I guess there's still some ongoing work to align with the Bioconductor folks, but that will probably take some more time, so, we go with this now.

**Comment by hexylena** [comment]
> I'm unsure about the PROXY_PREFIX and if this is still needed for other deployments than EU, ORG ...

if we want path based proxying to work, it probably needs to be supported somehow, but I guess that's a discussion with Sveinung

**Pull request merged**
